# -*- coding: utf-8 -*-
"""githubRepos.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1kW5g4-0E8p-WVFPalbUFmZKGKPPzXWIm

# Base
"""

!pip install fsspec

import requests

username = 'renancleyson-dev'
secret = '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'

base_url = 'https://api.github.com'

# fetch with credentials
def get(route, **kwargs):
  return requests.get(base_url + route, auth=(username, secret), **kwargs)

import json
import random
import pandas as pd
from io import StringIO

repo_attributes = ['id', 'full_name', 'description']

def get_random_repo():
  min = 0
  max = 10 ** 8

  params = { 'since': random.randint(min, max) }

  r = get('/repositories', params=params)

  return r.json()[0]

def get_branches(repo_fullname):
  r = get('/repos/' + repo_fullname + '/branches')
  return r.json()

def get_languages(repo_fullname):
  r = get('/repos/' + repo_fullname + '/languages')
  return r.json()

def get_commits(repo_fullname):
  params = { 'per_page': 100 }
  r = get('/repos/' + repo_fullname + '/commits', params=params)
  return r.json()

def get_created_date(repo_fullname):
  r = get('/repos/' + repo_fullname)
  return r.json().get('created_at')

data = []

for _ in range(200):
  random_repo = get_random_repo()
  random_repo = { attribute: random_repo[attribute] for attribute in repo_attributes }

  random_repo['branches'] = get_branches(random_repo['full_name'])
  random_repo['languages'] = get_languages(random_repo['full_name'])
  random_repo['commits'] = get_commits(random_repo['full_name'])
  random_repo['created_at'] = get_created_date(random_repo['full_name'])

  data.append(random_repo)

df = pd.read_json(StringIO(json.dumps(data)), orient='records')

df.to_csv('drive/MyDrive/IPI/repositories.csv')
df.head()